### ISSUE TITLE
I think it's weird that this defines a global function called Plugin

### ISSUE THREAD

**Issue by farzher** [Nijikokun/mithril-requests#1]
Is that necessary?

**Comment by nijikokun** [comment]
Do you have any suggested alternatives that support all three styles of export? 

I suppose I could move over to a ded style initializer

**Comment by farzher** [comment]
I don't have any experience with requirejs or whatever.
But wouldn't just wrapping it all in a self executing function work?
Is that what a `ded style initializer` is

**Comment by nijikokun** [comment]
Somewhat yes

**Comment by nijikokun** [comment]
@farzher can you test out `1.1.0` it should fix this issue

**Comment by farzher** [comment]
Looks good
